Handle .netrc file missing on Windows - Fixes #19
Swallow exceptions when the .netrc file isn't present.
Flow prompts for username and password in this case.

FileNotFoundError: [Errno 2] No such file or directory:
'C:\\Users\\Administrator\\.netrc'